### ISSUE TITLE
Processed died directly when roslaunch launch file

### ISSUE THREAD

**Issue by LiuHe76** [shinselrobots/nuitrack_body_tracker#4]
Hi, i encounter a weird problem. I followed the installation process step by step smoothly and there aren't any problems during the SDK testing. I just activate SDK based on trial version, and go through catkin_make process. Below is the message when I roslaunch nuitrack_body_tracker  nuitrack_body_tracker.launch:

... logging to /home/keith/.ros/log/11f5ff02-82e3-11e9-8afd-80fa5b179b12/roslaunch-keith-CW65S-31740.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://keith-CW65S:39805/

SUMMARY
========

PARAMETERS
 * /nuitrack_body_tracker_node/camera_color_frame: nuitrack_camera_link
 * /nuitrack_body_tracker_node/camera_depth_frame: nuitrack_camera_link
 * /rosdistro: kinetic
 * /rosversion: 1.12.14

NODES
  /
    nuitrack_body_tracker_node (nuitrack_body_tracker/nuitrack_body_tracker_node)

auto-starting new master
process[master]: started with pid [31750]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 11f5ff02-82e3-11e9-8afd-80fa5b179b12
process[rosout-1]: started with pid [31763]
started core service [/rosout]
process[nuitrack_body_tracker_node-2]: started with pid [31766]
[nuitrack_body_tracker_node-2] process has died [pid 31766, exit code -11, cmd /home/keith/catkin_ws/devel/lib/nuitrack_body_tracker/nuitrack_body_tracker_node __name:=nuitrack_body_tracker_node __log:=/home/keith/.ros/log/11f5ff02-82e3-11e9-8afd-80fa5b179b12/nuitrack_body_tracker_node-2.log].
log file: /home/keith/.ros/log/11f5ff02-82e3-11e9-8afd-80fa5b179b12/nuitrack_body_tracker_node-2*.log

**Comment by audrow** [comment]
@LiuHe76, I get the same error.  Did you find a way around it?
